name = "tomwe20"
author = "Tomzmn"
version = "2026.10.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03a8a49e5d574f66a2aca6819cd71a88a3c44ec23be99b2b778f1f9e24eeb914"

[versions]
minecraft = "1.7.10"
