name = "Noah Modpack"
author = "Tomzmn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e67e5960acb44b13a6b32dcec381c6ae08a8718144f854bf136b60580ab32acd"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
