name = "Noah Modpack"
author = "Tomzmn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9148c801533281bfdc4cf821df40409b490df04f87729f6d8a39c968e4781fb"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
