name = "Noah Modpack"
author = "Tomzmn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ee4cee96328ac8658cf6532b795d4a6dd8b9e65ff80c681e85d56e2420faac6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
