name = "noah26"
author = "Tomzmn"
version = "2026.10.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0d0f2700e70f5fc7c5621f52a2bc7fee4586ffddd873f0b95da3445ab5ba961"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
