name = "jarry26"
author = "Tomzmn"
version = "2026.10.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ce7e818d9bd00aa54ce10e91ba26fefc9058a37de197b46520ad59869fd0726"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
