name = "test27"
author = "Tomzmn"
version = "2026.10.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e619b3a37cf2d6bf7aa7be3cd912cf4a9dc3e0702b22ccc3ab08be20b792085"

[versions]
forge = "52.1.16"
minecraft = "1.21.1"
