name = "test27"
author = "Tomzmn"
version = "2026.10.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "934fb0535ddb2dd95540eba37c7a9947c6ee4ca6e0f62c01779289578bfed0a7"

[versions]
forge = "52.1.16"
minecraft = "1.21.1"
