name = "captive25"
author = "Tomzmn"
version = "2026.10.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bedbae880fbc4fb7bb1fb34dd4933e6fe3d660792086b3aba72de5a942b8d4ba"

[versions]
minecraft = "1.21.10"
